config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'application#index'

  get 'search' => 'application#search'
  get 'articles/search' => 'articles#search'
  get 'events/search' => 'events#search'
  get 'articles' => 'application#index'
  get 'events' => 'application#index'

  resources :articles
  resources :events
  resources :promotions
  resources :jobs
  resources :city_comments

  get 'user_account' => 'user_account#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :title, :description
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_job, only: [:update, :destroy]

	def index
		@jobs = Job.all
	end

	def show
    @job = Job.find(params[:id])
	end

	def new
		@job = current_user.jobs.new
		respond_to do |format|
      format.html { render layout: false }
    end
	end

	def create
		@job = current_user.jobs.new(job_params)
		if @job.save
			redirect_to @job
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @job.update(job_params)
			redirect_to @job
		else
			render 'edit'
		end
	end

	def destroy
		@job.delete
		flash[:notice] = "Emprego apagado com sucesso"
		redirect_to root_path
	end

	private
		def job_params
			params.require(:job).permit(:title, :description, :salary)
		end

		def set_job
			@job = current_user.jobs.find(params[:id])
		end
end

app/views/jobs/_form_jobs.html.erb
<%= simple_form_for @job do |f| %>
	<ul>
		<li> <%= f.input :title, placeholder: 'Título', label: false %> </li>
		<li> <%= f.input :description, placeholder: 'Descrição', as: :text, label: false %></li>
		<li>
			<%= f.input :salary %>
		</li>
	</ul>

	<div class="submit-area">
		<%= f.button :submit, "Enviar"%>
	</div>
<% end %>

app/views/jobs/edit.html.erb
<div class="share-article">
  <div class="create-article">
    <h2><%= t('page.jobs.form_edit_title') %></h2>
    <%= render 'form_jobs' %>
  </div>
</div>

app/views/jobs/index.html.erb
<h2><%= t('page.jobs.title') %></h2>
<% @jobs.each do |job| %>
  <div class="card">
    <a href="<%= job_path(job) %>">
      <%= render partial: 'layouts/author', locals: { article: job } %>

      <div class="mini-news">
        <h4><%= job.title %></h4>
        <p><%= job.description %></p>
        <span>Salary: <%= job.salary %> </span>
      </div>
    </a>
  </div>
<% end %>

app/views/jobs/new.html.erb
<div class="share-article">
  <div class="create-article">
    <h2><%= t('page.jobs.form_new_title') %></h2>
    <%= render 'form_jobs' %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="card full">
	<div class="short-new">

		<div class="">
			<h4><%= @job.title %></h4>
			<p><%= @job.description %></p>
			<p>Salário: <%= @job.salary %></p>
		</div>

	</div>

	<% if current_user == @job.user %>
		<%= link_to "Editar", edit_job_path(@job), class: "left"; %>
		<%= link_to "Deletar", job_path(@job), method: :delete, class: "right" %>
	<% end %>
</div>