config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'application#index'

  get 'search' => 'application#search'
  get 'articles/search' => 'articles#search'
  get 'events/search' => 'events#search'
  get 'articles' => 'application#index'
  get 'events' => 'application#index'

  resources :articles
  resources :events
  resources :promotions
  resources :jobs
  resources :city_comments

  get 'user_account' => 'user_account#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_one :picture, as: :imageable, dependent: :destroy
  has_one :location, as: :locationable, dependent: :destroy
  accepts_nested_attributes_for :picture, :location

  validates_presence_of :title, :description, :date

  searchkick merge_mappings: true, mappings: {
    event: {
      dynamic: 'strict',
      properties: {
        id: { type: 'integer' },
        title: { type: 'string' },
        photo_url: { type: 'string' },
        author_name: { type: 'string' },
        author_picture: { type: 'string'},
        city: { type: 'string' },
        state: { type: 'string' },
        country: { type: 'string' },
        location: { type: 'geo_point' },
        date: { type: 'date' }
      }
    }
  }

  def search_data
    {
      id: id,
      title: title,
      photo_url: picture.photo.url(:medium),
      author_name: user.name,
      author_picture: user.image,
      city: location.city,
      state: location.state,
      country: location.country,
      location: {
        lat: location.latitude,
        lon: location.longitude
      },
      date: date
    }
  end

  def self.search_by_location(latitude, longitude, distance)
    lat = latitude.to_f
    lon = longitude.to_f
    distance_str = "#{distance}km"

    events = Event.search('*', load: false,
      where: {
        location: {
          near: [lat, lon],
          within: distance_str
        }
      },
      sort: { created_at: { order: 'desc' } }
    )

    events.as_json(except: [:_id, :_index, :_type, :_score])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :search]
  before_action :set_event, only: [:edit, :update, :destroy]

  def search
    render json: Event.search_by_location(
      params[:latitude],
      params[:longitude],
      params[:distance]
    )
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.new
    respond_to do |format|
      format.html { render layout: false }
    end
  end

  def create
    @event = current_user.events.new(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "Evento alterado"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.delete
    flash[:notice] = "Evento deletado"
    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :date, :user_id, picture_attributes: [:photo])
  end

  def set_event
    @event = current_user.events.find(params[:id])
  end
end

app/views/events/_form_events.html.erb
<%= simple_form_for @event do |f| %>
	<ul>
		<li> <%= f.input :title, placeholder: 'Título', label: false %> </li>
		<li> <%= f.input :description, placeholder: 'Descrição', as: :text, label: false %></li>
		<li>
			<%= f.input :date, label: "Quando?", as: :date, start_year: Date.today.year, end_year: Date.today.year + 5, order: [:day, :month, :year] %>
		</li>

		<li>Anexar:</li>
		<li	class="file-upload">
				<%= image_tag "icon-camera.png" %>
				<%= f.fields_for :picture_attributes do |picture_fields| %>
					<%= picture_fields.file_field :photo %> 
				<% end %>
		</li>
	</ul>

	<div class="submit-area">
		<%= f.button :submit, "Enviar"%>
	</div>
<% end %>

app/views/events/edit.html.erb
<div class="share-article">
  <div class="create-article">
    <h2><%= t('page.events.form_edit_title') %></h2>
    <%= render 'form_events' %>
  </div>
</div>

app/views/events/index.html.erb
<script id="events-template" type="text/x-handlebars-template">
  <div data-contentLoader-container>
    <h2><%= t('page.events.title') %><span data-title></span></h2>
    {{#if this}}
      {{#each this}}
        <a class='grid-50' href="events/{{id}}">
          <article class="card big-height">
            <img src="{{photo_url}}" class="img-article">

            <div class="mini-news">
              <div class="author">
                <img src="{{author_picture}}" class="user-logo">
                por: {{author_name}} - {{city}} - {{prettifyDate date}}
              </div>

              <h4>{{title}}</h4>
            </div>

          </article>
        </a>
      {{/each}}
    {{else}}
      <%= t('page.no_content') %>
    {{/if}}
  </div>
</script>

app/views/events/new.html.erb
<div class="share-article">
  <div class="create-article">
    <h2><%= t('page.events.form_new_title') %></h2>
    <%= render 'form_events' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="card full">
	<div class="short-new">

		<div class="img-wrapper">
			<% if @event.picture %>
				<%= image_tag(@event.picture.photo.url(:medium), class: "img-article") %>
			<% end %>
			<%= render partial: 'layouts/author', locals: { article: @event } %>
		</div>

		<div class="">
			<span>Quando: <%= @event.date.day %>/<%= @event.date.month %>/<%= @event.date.year %></span>
			<h4><%= @event.title %></h4>
			<p><%= @event.description %></p>
		</div>

	</div>

	<% if current_user == @event.user %>
		<%= link_to "Editar", edit_event_path(@event), class: "left"; %>
		<%= link_to "Deletar", event_path(@event), method: :delete, class: "right" %>
	<% end %>
</div>