config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'application#index'

  get 'search' => 'application#search'
  get 'articles/search' => 'articles#search'
  get 'events/search' => 'events#search'
  get 'articles' => 'application#index'
  get 'events' => 'application#index'

  resources :articles
  resources :events
  resources :promotions
  resources :jobs
  resources :city_comments

  get 'user_account' => 'user_account#index'

end

app/controllers/user_account_controller.rb
class UserAccountController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = current_user.articles.all
    @events = current_user.events.all
    @jobs = current_user.jobs.all
    @city_comments = current_user.city_comments.all
  end
end

app/views/user_account/index.html.erb
<h2>Meus Artigos</h2>

<% unless @articles.empty? %>
  <div class='grid-50 user-account'>
    <h3>Artigos</h3>
    <% @articles.each do |article| %>
      <p><%= link_to article.title, article_path(article) %></p>
      <time>criado em: <%= article.updated_at.strftime("%d/%m/%Y") %></time>
    <% end %>
  </div>
<% end %>

<% unless @events.empty? %>
  <div class='grid-50 user-account'>
    <h3>Eventos</h3>
    <% @events.each do |event| %>
      <p><%= link_to event.title, event_path(event) %></p>
      <time>criado em: <%= event.updated_at.strftime("%d/%m/%Y") %></time>
    <% end %>
  </div>
<% end %>

<% unless @jobs.empty? %>
  <div class='grid-50 user-account'>
    <h3>Empregos</h3>
    <% @jobs.each do |job| %>
      <p><%= link_to job.title, job_path(job) %></p>
      <time>criado em: <%= job.updated_at.strftime("%d/%m/%Y") %></time>
    <% end %>
  </div>
<% end %>

<% unless @city_comments.empty? %>
  <div class='grid-50 user-account'>
    <h3>Recados para Prefeitura</h3>
    <% @city_comments.each do |city_comment| %>
      <p><%= link_to city_comment.title, city_comment_path(city_comment) %></p>
      <time>criado em: <%= city_comment.updated_at.strftime("%d/%m/%Y") %></time>
    <% end %>
  </div>
<% end %>